- name: Launch an AWS instance
  hosts: localhost
  gather_facts: false
  vars:
    keypair: macbook1
    instancetype: t2.micro
    image: ami-0b59bfac6be064b78
    region: us-east-2
  tasks:
  - name: Launch instance
    ec2:
      key_name: '{{ keypair }}'
      group: default
      instance_type: '{{ instancetype }}'
      image: '{{ image }}'
      wait: true
      region: '{{ region }}'
      aws_access_key: AWSPUBLICKEY
      aws_secret_key: AWSSECRETKEY
    register: ec2
  - name: PRint all ec2 variables
    debug: var=ec2

