- name: Launch an AWS instance
  hosts: localhost
  gather_facts: false
  vars:
    keypair: macbook1
    instancetype: t2.micro
    image: ami-0b59bfac6be064b78
    region: us-east-2
  tasks:
  - name: Create and Launch instance
    ec2:
      key_name: '{{ keypair }}'
      group: default
      instance_type: '{{ instancetype }}'
      image: '{{ image }}'
      wait: true
      count: 1
      state: present
      region: '{{ region }}'
      aws_access_key: AKIAINU72ZBT5QMFL5UA
      aws_secret_key: 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
    register: ec2

  - name: Print all ec2 variables
    debug: var=ec2

  - name: Wait for SSH to come up
    delegate_to: "{{ item.public_dns_name }}"
    wait_for_connection:
      delay: 60
      timeout: 320
      with_items: "{{ ec2.instances }}"

  - name: Terminate instances that were previously launched
    ec2:
      state: 'absent'
      instance_ids: '{{ ec2.instance_ids }}'

