- name: Launch an AWS instance
  hosts: localhost
  gather_facts: false
  vars:
    keypair: macbook1
    instancetype: t2.micro
    image: ami-0b59bfac6be064b78
    region: us-east-2
  tasks:
  - name: Create and Launch instance
    ec2:
      key_name: '{{ keypair }}'
      group: default
      instance_type: '{{ instancetype }}'
      image: '{{ image }}'
      wait: true
      count: 1
      state: present
      region: '{{ region }}'
      aws_access_key: AKIAINU72ZBT5QMRL5UA
      aws_secret_key: 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
    register: ec2

  - name: Print all ec2 variables
    debug: var=ec2

